### ISSUE TITLE
Error running generator task

### ISSUE THREAD

**Issue by davidaustinarcher** [KennaSecurity/toolkit#106]
Hi 👋

I was trying to run the generator task and ran into an error:

`Status: Downloaded newer image for quay.io/kennasecurity/toolkit:latest
quay.io/kennasecurity/toolkit:latest
Running: Kenna::Toolkit::KennaDemoDataGenerator
[+] (20210119155811) Setting kenna_api_host to default value: api.kennasecurity.com
[+] (20210119155811) Setting output_directory to default value: output/generator
[+] (20210119155811) Got option: task: generator
[+] (20210119155811) Got option: kenna_api_host: api.kennasecurity.com
[+] (20210119155811) Got option: kenna_connector_id: 
[+] (20210119155811) Got option: output_directory: output/generator
[+] (20210119155811) 
[+] (20210119155811) Launching the Kenna Demo Data Generator task!
[+] (20210119155811) 
Traceback (most recent call last):
        6: from toolkit.rb:48:in '<main>'
        5: from /opt/app/toolkit/tasks/generator/generator.rb:95:in 'run'
        4: from /opt/app/toolkit/tasks/generator/generator.rb:95:in 'each'
        3: from /opt/app/toolkit/tasks/generator/generator.rb:115:in 'block in run'
        2: from /opt/app/toolkit/lib/kdi/kdi_helpers.rb:122:in 'create_kdi_asset_vuln'
        1: from /opt/app/toolkit/lib/kdi/kdi_helpers.rb:77:in 'find_or_create_kdi_asset'
/opt/app/toolkit/lib/kdi/kdi_helpers.rb:77:in 'fetch': key not found: nil (KeyError)`

My command was:

`docker pull quay.io/kennasecurity/toolkit && docker run -it quay.io/kennasecurity/toolkit task=generator`

Could you advise if I did something incorrectly?

Thanks,

David

**Comment by lindambrown** [comment]
Found a bug! Thank you very much!!!! Please try again, it should work now. 

Linda

**Comment by jgamblin** [comment]
@davidaustinarcher I am going to close this but if the issue still exists please let us know.
