### ISSUE TITLE
podman on linux (only)?

### ISSUE THREAD

**Issue by jcran** [KennaSecurity/toolkit#156]
README.md currently indicates only podman on linux - which, from personal experience definitely isnt the case. Can you adjust to indicate Docker or other container platforms are also supported?

i can only blame @jdoss for this. Blamed with <3

**Comment by jgamblin** [comment]
Thansk! We will get the document updated!

**Comment by jcran** [comment]
🙌

**Comment by jdoss** [comment]
@jcran How dare you!
