### ISSUE TITLE
GitHub Action Container Runs Fail - ./scripts/entrypoint.sh: no such file or directory: unknown

### ISSUE THREAD

**Issue by resnickio** [KennaSecurity/toolkit#277]
Running kennasecurity/toolkit containers as part of a GitHub Action fails with the below error, however the same commands work in a local docker environment.

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "./scripts/entrypoint.sh": stat ./scripts/entrypoint.sh: no such file or directory: unknown.
```

GitHub Action debug log, workflow, and action files have been included below.

[3_Dependabot KDI upload.txt](https://github.com/KennaSecurity/toolkit/files/7618836/3_Dependabot.KDI.upload.txt)
[kennaToolkitWorkflow.yaml.txt](https://github.com/KennaSecurity/toolkit/files/7618848/kennaToolkitWorkflow.yaml.txt)
[action.yaml.txt](https://github.com/KennaSecurity/toolkit/files/7618860/action.yaml.txt)

**Comment by jgamblin** [comment]
@resnickio becuase of the need to pass secrets it is easier to use the toolkit outside of docker.  Here is a repository that I created to demo how to run the toolkit using an action. 
`
[Kenna Toolkit Github Actions](https://github.com/KennaSecurity/Kenna-Actions/ )

Let me know if this helps get you up and running.

**Comment by resnickio** [comment]
Thanks @jgamblin, I tried running a help task as a test and it looks like the new github_dependabot merge may be causing an issue? I've included the error message and the workflow below. Please let me know if you need more information.

```yaml
name: KennaSecurity/toolkit Help Task
on: workflow_dispatch

jobs:
  Kenna-Action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Toolkit Repository
      uses: actions/checkout@v2
      with:
        repository: KennaSecurity/toolkit
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install Dependencies
      run: bundle install --without development test
    - name: Run Toolkit
      run: exec bundle exec ruby toolkit.rb task=help
```

```
##[debug]Evaluating condition for step: 'Run Toolkit'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Run Toolkit
##[debug]Loading inputs
##[debug]Loading env
Run exec bundle exec ruby toolkit.rb task=help
##[debug]/usr/bin/bash -e /home/runner/work/_temp/94c50348-e358-4b7e-a5a9-6a71430283bd.sh
/home/runner/work/<myRepo>/<myRepo>/tasks/connectors/github_dependabot/lib/github_dependabot_client.rb:3:in `require': cannot load such file -- byebug (LoadError)
	from /home/runner/work/<myRepo>/<myRepo>/tasks/connectors/github_dependabot/lib/github_dependabot_client.rb:3:in `<top (required)>'
	from /home/runner/work/<myRepo>/<myRepo>/tasks/connectors/github_dependabot/github_dependabot.rb:3:in `require_relative'
	from /home/runner/work/<myRepo>/<myRepo>/tasks/connectors/github_dependabot/github_dependabot.rb:3:in `<top (required)>'
	from /home/runner/work/<myRepo>/<myRepo>/lib/toolkit.rb:44:in `require_relative'
	from /home/runner/work/<myRepo>/<myRepo>/lib/toolkit.rb:44:in `block in <top (required)>'
	from /home/runner/work/<myRepo>/<myRepo>/lib/toolkit.rb:44:in `each'
	from /home/runner/work/<myRepo>/<myRepo>/lib/toolkit.rb:44:in `<top (required)>'
	from toolkit.rb:5:in `require_relative'
	from toolkit.rb:5:in `<main>'
Error: Process completed with exit code 1.
##[debug]Finishing: Run Toolkit
```

**Comment by jgamblin** [comment]
@resnickio sorry for the delay but this should work now.  We have added a native test to our testing suite so this should work moving forward. 

https://github.com/KennaSecurity/toolkit/actions/runs/1523202331

**Comment by jgamblin** [comment]
@resnickio It looks like we have this fixed and have set up an action on our end to test.  
https://github.com/KennaSecurity/toolkit/blob/master/.github/workflows/nativeruby.yml

Can you please give it a try?
