### ISSUE TITLE
Kenna - AWS inspector

### ISSUE THREAD

**Issue by dmange3190** [KennaSecurity/toolkit#389]
I am getting this error when I imported json file of inspector findings.

Invalid JSON caused AWS Inspector KDI to fail. The JSON was improper because of: The property '#/' did not contain a required property of 'assets'.

How do I convert the inspector json findings into the format KDI JSON FORMAT v2 ?

**Comment by mukhansk** [comment]
This is a bug from our side. We will add KDI version 2 soon. Thanks

**Comment by annapoltieva** [comment]
@dmange3190 I've added KDI version 2 support here https://github.com/dmange3190)https://github.com/KennaSecurity/toolkit/pull/405

But I don't have the credentials, so can you please verify that it does or doesn't work on your end

**Comment by annapoltieva** [comment]
Also, the KDI json versions are described [here](https://help.kennasecurity.com/hc/en-us/articles/360026413111-Kenna-Data-Importer-JSON-Connector-)
