### ISSUE TITLE
Expanse issues creates duplicate files

### ISSUE THREAD

**Issue by venkatawunnava** [KennaSecurity/toolkit#395]
When Expanse issue is run with optional parameters, instead of fetching the data for give param the toolkit fetches/creates duplicate files with same data which is ignored during connector run. 

Steps to replicate 
1. Run the task with the optional parameter `issue_types=MissingCacheControlHeader`

Expected
the run should fetch only vulns related to the `issue_type` and create only one file

Actual
The run creates 4 files with same data

**Comment by mukhansk** [comment]
Resolved here: 
https://github.com/KennaSecurity/toolkit/pull/427
